version: '3.8'

services:
  mongodb:
    image: mongo:5.0.2
    ports:
      - 27016:27017
    volumes:
      - db:/data/db

  app:
    depends_on:
      - mongodb
    build: .
    ports:
      - 5000:5000
    environment:
      - PORT=${PORT}
      - DB_URI=${DOCKER_DB_URI}
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
      - JWT_EXPIRY_TIME=${JWT_EXPIRY_TIME}

volumes:
  db:
