name: Continuous integration

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create mongoDB Docker container for API testing
        uses: DigiPie/mongo-action@v1.0.1
      - name: Install npm packages
        run: npm install

      - name: Run `npm run build` to build Typescript into Javascript
        run: npm run build

      - name: Run `npm test`
        run: npm test

        env:
          CI: true
          PORT: 5111
          DB_URI: mongodb://localhost:27017/test
          STARTING_CREW_NUMBER: 3
          SHIP_CAPACITY: 5
          STARTING_SHIP_NUMBER: 3
          MOTHERSHIP_CAPACITY: 9
